name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  APP_NAME: wisecow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: sourabhapatil24/wisecow:${{ github.run_number }}
        
  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          repository: sourabh451/wisecow-app
          ref: 'master'
      - name: setup git config
        run: |
          git config --global user.email "er.sourabhapatil@gmail.com"
          git config --global user.name "Sourabha Patil"
          sed -i "s/${{ env.APP_NAME }}.*/${{ env.APP_NAME }}:${{ github.run_number }}/g"  deployment.yaml
          git add -A
          git commit -am "Update deployment image to version ${{ github.run_number }}" 
      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git push https://x-access-token:${GH_PAT}@github.com/sourabh451/wisecow-app HEAD:master
          
        
